M48
; DRILL file {KiCad (6.0.7)} date Tue Mar 21 01:18:28 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-21T01:18:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X116.414Y-134.239
X116.414Y-62.058
X177.972Y-62.058
X177.972Y-134.284
T0
M30
